from langchain_text_splitters import CharacterTextSplitter
text_splitter = CharacterTextSplitter(chunk_size =500 , chunk_overlap = 50,  separator=" ")
text = [
    """Good morning everyone, how are you guys today? I hope you are all feeling fresh, positive, and ready to start the day with good energy. Every morning gives us a new opportunity to learn something new, improve ourselves, and move one step closer to our goals. A good start in the morning often sets the tone for the entire day, so staying calm, focused, and motivated is very important. Life is a journey where small efforts made daily create big results over time. Sometimes progress feels slow, but consistency always matters more than speed. Challenges are a normal part of growth, and each challenge teaches us valuable lessons that help us become stronger and wiser. Mistakes should never discourage us, because they are proof that we are trying and learning. Confidence grows when we trust ourselves and keep practicing, even when things feel difficult. Time is one of the most valuable resources we have, and using it wisely helps us stay productive and stress-free. Staying disciplined, patient, and focused allows us to handle pressure better and make smarter decisions. It is important to stay curious, ask questions, and never stop learning, because knowledge opens doors to new opportunities. Positive thinking improves not only our mindset but also the way we interact with others. When we support each other and work together, even tough tasks become easier. Success does not come overnight, but daily effort, dedication, and persistence slowly shape it. Taking care of our health, maintaining balance, and staying grateful for small achievements keeps us mentally strong. Every day may not be perfect, but there is always something good to appreciate. With the right attitude, clear goals, and steady effort, we can make today meaningful and productive for ourselves and for the people around us.
    Good morning everyone, how are you guys today? I hope you are all feeling fresh, positive, and ready to start the day with good energy. Every morning gives us a new opportunity to learn something new, improve ourselves, and move one step closer to our goals. A good start in the morning often sets the tone for the entire day, so staying calm, focused, and motivated is very important. Life is a journey where small efforts made daily create big results over time. Sometimes progress feels slow, but consistency always matters more than speed. Challenges are a normal part of growth, and each challenge teaches us valuable lessons that help us become stronger and wiser. Mistakes should never discourage us, because they are proof that we are trying and learning. Confidence grows when we trust ourselves and keep practicing, even when things feel difficult. Time is one of the most valuable resources we have, and using it wisely helps us stay productive and stress-free. Staying disciplined, patient, and focused allows us to handle pressure better and make smarter decisions. It is important to stay curious, ask questions, and never stop learning, because knowledge opens doors to new opportunities. Positive thinking improves not only our mindset but also the way we interact with others. When we support each other and work together, even tough tasks become easier. Success does not come overnight, but daily effort, dedication, and persistence slowly shape it. Taking care of our health, maintaining balance, and staying grateful for small achievements keeps us mentally strong. Every day may not be perfect, but there is always something good to appreciate. With the right attitude, clear goals, and steady effort, we can make today meaningful and productive for ourselves and for the people around us."""
]
docs = text_splitter.create_documents(text)
i=1
for c in docs:
    print(f"\nChunk {i} -> {c.page_content}")
    i+=1